---
name: Feature request
about: Suggest an idea for this package
labels: enhancement
---

<!-- 
Please fill in a brief description of the request here.
-->

## Detailed description

<!--
Describe the intended feature in detail.
-->